baseurl         = ""
theme           = "casper-two"
languageCode    = "zh-CN"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "盗梦空间"
  subtitle    = ""

  cover       = "uploads/pexels-photo-1142950.jpeg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  #twitterName = "faketryghost"
  #fbName = "fakeghost"
  githubName = "lduhejian"

  logo = ""
  orgName = "何健"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "何健"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "北京"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "coder developer"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "PHP"
  url = "/tags/php/"
  weight = 100

[[menu.main]]
  name = "Food"
  url = "/categories/food/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95
